//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SligoCS.Web.WI {
    
    
    /// <summary>
    /// AttendancePage class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class AttendancePage {
        
        /// <summary>
        /// nlrSTYP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavSchoolType nlrSTYP;
        
        /// <summary>
        /// nlrVwBy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrVwBy;
        
        /// <summary>
        /// linkGroupAll control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkGroupAll;
        
        /// <summary>
        /// linkGroupGender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkGroupGender;
        
        /// <summary>
        /// linkGroupRace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkGroupRace;
        
        /// <summary>
        /// linkGroupGrade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkGroupGrade;
        
        /// <summary>
        /// linkGroupDisability control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkGroupDisability;
        
        /// <summary>
        /// linkGroupEconDisadv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkGroupEconDisadv;
        
        /// <summary>
        /// linkGroupEngLangProf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkGroupEngLangProf;
        
        /// <summary>
        /// nlrCompareTo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavCompareTo nlrCompareTo;
        
        /// <summary>
        /// GraphPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel GraphPanel;
        
        /// <summary>
        /// barChart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.GraphBarChart barChart;
        
        /// <summary>
        /// AttendanceDataGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebSupportingClasses.WinssDataGrid AttendanceDataGrid;
        
    }
}
