//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SligoCS.Web.WI {
    
    
    /// <summary>
    /// MoneyPage class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class MoneyPage {
        
        /// <summary>
        /// DataPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel DataPanel;
        
        /// <summary>
        /// nlrShow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrShow;
        
        /// <summary>
        /// linkRevExpRevenue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkRevExpRevenue;
        
        /// <summary>
        /// linkRevExpExpenditure control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkRevExpExpenditure;
        
        /// <summary>
        /// nlrType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrType;
        
        /// <summary>
        /// linkCTCost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkCTCost;
        
        /// <summary>
        /// linkCTTotalEducation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkCTTotalEducation;
        
        /// <summary>
        /// linkCTCurrentEducation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkCTCurrentEducation;
        
        /// <summary>
        /// nlrCompareTo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavCompareTo nlrCompareTo;
        
        /// <summary>
        /// GraphPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel GraphPanel;
        
        /// <summary>
        /// barChart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.GraphBarChart barChart;
        
        /// <summary>
        /// DistrictDataProvided control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal DistrictDataProvided;
        
        /// <summary>
        /// RevenueDataGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebSupportingClasses.WinssDataGrid RevenueDataGrid;
        
        /// <summary>
        /// ExpenditureDataGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebSupportingClasses.WinssDataGrid ExpenditureDataGrid;
        
        /// <summary>
        /// BottomLinkMoreData1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkMoreData BottomLinkMoreData1;
        
        /// <summary>
        /// BottomLinkViewReport1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkViewReport BottomLinkViewReport1;
        
        /// <summary>
        /// BottomLinkViewProfile1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkViewProfile BottomLinkViewProfile1;
        
        /// <summary>
        /// BottomLinkDownload1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkDownload BottomLinkDownload1;
        
        /// <summary>
        /// BottomLinkWhatToConsider1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkWhatToConsider BottomLinkWhatToConsider1;

        protected global::System.Web.UI.WebControls.Panel pnlMessage;    
    }
}
