//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SligoCS.Web.WI {
    
    
    /// <summary>
    /// ACTPage class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class ACTPage {
        
        /// <summary>
        /// nlrSelectYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavSelectYear nlrSelectYear;
        
        /// <summary>
        /// nlrShow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrShow;
        
        /// <summary>
        /// ACTlink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus ACTlink;
        
        /// <summary>
        /// APlink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus APlink;
        
        /// <summary>
        /// nlrSubject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrSubject;
        
        /// <summary>
        /// linkACTSubjReading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkACTSubjReading;
        
        /// <summary>
        /// linkACTSubjEnglish control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkACTSubjEnglish;
        
        /// <summary>
        /// linkACTSubjMath control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkACTSubjMath;
        
        /// <summary>
        /// linkACTSubjScience control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkACTSubjScience;
        
        /// <summary>
        /// linkACTSubjSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus linkACTSubjSummary;
        
        /// <summary>
        /// nlrVwByGroup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavViewByGroup nlrVwByGroup;
        
        /// <summary>
        /// nlrCompareTo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavCompareTo nlrCompareTo;
        
        /// <summary>
        /// ChangeSelectedSchoolOrDistrict control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.ChangeSelectedSchoolOrDistrictLink ChangeSelectedSchoolOrDistrict;
        
        /// <summary>
        /// barChart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.GraphBarChart barChart;
        
        /// <summary>
        /// TextForRaceInBottomLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel TextForRaceInBottomLink;
        
        /// <summary>
        /// BottomLinkViewReport1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkViewReport BottomLinkViewReport1;
        
        /// <summary>
        /// BottomLinkViewDistrictReport1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkViewDistrictReport BottomLinkViewDistrictReport1;
        
        /// <summary>
        /// BottomLinkViewProfile1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkViewProfile BottomLinkViewProfile1;
        
        /// <summary>
        /// BottomLinkWhyNotReported1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkWhyNotReported BottomLinkWhyNotReported1;
        
        /// <summary>
        /// BottomLinkDownload1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkDownload BottomLinkDownload1;
    }
}
