//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SligoCS.Web.WI {
    
    
    /// <summary>
    /// ComparePerformance class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class ComparePerformance {
        
        /// <summary>
        /// nlrGrade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrGrade;
        
        /// <summary>
        /// grade3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus grade3;
        
        /// <summary>
        /// grade4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus grade4;
        
        /// <summary>
        /// grade5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus grade5;
        
        /// <summary>
        /// grade6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus grade6;
        
        /// <summary>
        /// grade7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus grade7;
        
        /// <summary>
        /// grade8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus grade8;
        
        /// <summary>
        /// grade9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus grade9;
        
        /// <summary>
        /// grade10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus grade10;
        
        /// <summary>
        /// gradeCombined control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus gradeCombined;
        
        /// <summary>
        /// nlrSubject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrSubject;
        
        /// <summary>
        /// HyperLinkPlus2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus HyperLinkPlus2;
        
        /// <summary>
        /// HyperLinkPlus3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus HyperLinkPlus3;
        
        /// <summary>
        /// HyperLinkPlus4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus HyperLinkPlus4;
        
        /// <summary>
        /// HyperLinkPlus5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus HyperLinkPlus5;
        
        /// <summary>
        /// HyperLinkPlus6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus HyperLinkPlus6;
        
        /// <summary>
        /// nlrWkceCombined control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrWkceCombined;
        
        /// <summary>
        /// HyperLinkPlus13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus HyperLinkPlus13;
        
        /// <summary>
        /// HyperLinkPlus14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.Base.WebServerControls.WI.HyperLinkPlus HyperLinkPlus14;
        
        /// <summary>
        /// GraphPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel GraphPanel;
        
        /// <summary>
        /// barChart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.GraphBarChart barChart;

        /// <summary>
        /// TruancyDataGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebSupportingClasses.WinssDataGrid CompareContinuingDataGrid;
        
        /// <summary>
        /// BottomLinkViewReport1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkViewReport BottomLinkViewReport1;
        
        /// <summary>
        /// BottomLinkViewProfile1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkViewProfile BottomLinkViewProfile1;
        
        /// <summary>
        /// BottomLinkWhyNotReported1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkWhyNotReported BottomLinkWhyNotReported1;
        
        /// <summary>
        /// BottomLinkDownload1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkDownload BottomLinkDownload1;
    }
}
