//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SligoCS.Web.WI {
    
    
    /// <summary>
    /// ExpServices class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class ExpServices {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// PostExpulsionDataGrid
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebSupportingClasses.WinssDataGrid PostExpulsionDataGrid;

        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        /// <summary>
        /// ChangeSelectedSchoolOrDistrict control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.ChangeSelectedSchoolOrDistrictLink ChangeSelectedSchoolOrDistrict;
        
        /// <summary>
        /// BottomLinkEnrollmentCounts1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkEnrollmentCounts BottomLinkEnrollmentCounts1;

        /// <summary>
        /// BottomLinkViewReport1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkViewReport BottomLinkViewReport1;

        /// <summary>
        /// BottomLinkViewProfile1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkViewProfile BottomLinkViewProfile1;

        /// <summary>
        /// BottomLinkWhyNotReported1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkWhyNotReported BottomLinkWhyNotReported1;

        /// <summary>
        /// BottomLinkDownload1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkDownload BottomLinkDownload1;

        /// <summary>
        /// barChart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.GraphHorizBarChart barChart;
    }
}
