//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1873
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SligoCS.Web.WI {
    
    
    /// <summary>
    /// StateTestsScatterplot class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class StateTestsScatterplot {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// BottomLinkViewProfile1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkViewProfile BottomLinkViewProfile;

        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrShowDiff;
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrLocation;
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrRelateTo;
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrSubject;
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrLevel;
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow nlrGrade;

        /// <summary>
        /// scatterplot control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.GraphScatterplot scatterplot;

        /// <summary>
        /// WinssDataGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebSupportingClasses.WinssDataGrid StateTestsScatterDataGrid;

        protected global::System.Web.UI.WebControls.Panel pnlMessage;
    }
}
