//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SligoCS.Web.WI.WebUserControls
{

    public partial class NavSelectYear
    {
        protected global::SligoCS.Web.WI.WebUserControls.NavigationLinkRow SelectYear_Row;

        protected global::System.Web.UI.WebControls.Label lblControlList;
    }
}
