//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SligoCS.Web.WI {
    
    
    /// <summary>
    /// Truancy class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class Truancy {
        
        /// <summary>
        /// ParamsLinkBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.ParamsLinkBox ParamsLinkBox1;
        
        /// <summary>
        /// GraphPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel GraphPanel;
        
        /// <summary>
        /// barChart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.GraphBarChart barChart;
        
        /// <summary>
        /// ChangeSelectedSchoolOrDistrict control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink ChangeSelectedSchoolOrDistrict;
        
        /// <summary>
        /// SligoDataGrid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebServerControls.WI.SligoDataGrid SligoDataGrid1;
        
        /// <summary>
        /// DefPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel DefPanel;
        
        /// <summary>
        /// BottomLinkEnrollmentCounts1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkEnrollmentCounts BottomLinkEnrollmentCounts1;
        
        /// <summary>
        /// BottomLinkViewReport1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkViewReport BottomLinkViewReport1;
        
        /// <summary>
        /// BottomLinkViewProfile1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkViewProfile BottomLinkViewProfile1;
        
        /// <summary>
        /// BottomLinkWhyNotReported1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkWhyNotReported BottomLinkWhyNotReported1;
        
        /// <summary>
        /// BottomLinkDownload1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SligoCS.Web.WI.WebUserControls.BottomLinkDownload BottomLinkDownload1;
    }
}
